-- This module is the root of the YauTianDonaldsonCanonicalLaneLean Lean proof package.
import YauTianDonaldsonCanonicalLaneLean.Basic
import YauTianDonaldsonCanonicalLaneLean.SourcePackage
import YauTianDonaldsonCanonicalLaneLean.SourceDependencies
import YauTianDonaldsonCanonicalLaneLean.Formalization
import YauTianDonaldsonCanonicalLaneLean.ReviewerBridge
import YauTianDonaldsonCanonicalLaneLean.TheoremStatement
import YauTianDonaldsonCanonicalLaneLean.MathlibObjects
import YauTianDonaldsonCanonicalLaneLean.AdmissibleClass
import YauTianDonaldsonCanonicalLaneLean.Projection
import YauTianDonaldsonCanonicalLaneLean.BridgeLemmas
import YauTianDonaldsonCanonicalLaneLean.GateLemmas
import YauTianDonaldsonCanonicalLaneLean.FinalTheorem
import YauTianDonaldsonCanonicalLaneLean.MathlibStatement
